name: foo
space: default
labels:
  foo: bar
annotations:
  bar: foo
env:
  CF_ROOT: /root
  SERVER_PORT: "8080"
route:
- route: foo.default.cluster.io/
  protocol: http2
service:
- name: mysql
  parameters:
    DB_NAME: default
process:
- type: web
  command:
  - /bin/sh
  - echo
  - hello world >index.html
  - '&&'
  - python3
  - -m
  - http.server
  - $SERVER_PORT
  memory: 128MB
  healthCheck:
    endpoint: localhost:8080/
    type: http
  readinessCheck:
    endpoint: localhost:8080/
    type: http
stack: default
docker:
  image: python:latest