name: foo
space: default
labels:
  foo: bar
annotations:
  bar: foo
version: ""
env:
  CF_ROOT: /root
  SERVER_PORT: "8080"
route:
- route: foo.default.cluster.io/
  protocol: http2
service:
- name: mysql
  parameters:
    DB_NAME: default
process:
- type: web
  command:
  - /usr/bin/echo hello world>index.html; /usr/local/bin/python3 -m http.server $SERVER_PORT
  memory: 128Mi
  healthCheck:
    endpoint: localhost:8080/
    timeout: 30
    interval: 30
    type: http
  readinessCheck:
    endpoint: localhost:8080/
    timeout: 30
    interval: 30
    type: http
  instances: 1
  logRateLimit: 16K
  lifecycle: docker
stack: default
timeout: 0
docker:
  image: python:3
instances: 1
