{{- if .Values.route -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- include "metadata" . |nindent 2}}
spec:
  rules:
    {{- range .Values.routes }}
      {{- $url:= urlParse (printf "http://%s" .route) }}
    - host: {{ $url.hostname }}
      http:
        paths:
          - path: {{ $url.path }}
            pathType: Exact
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  number: {{ dig "SERVER_PORT" "" $.Values.env }}
    {{- end }}
{{- end -}}
