apiVersion: v1
kind: Service
metadata:
{{- include "metadata" . |nindent 2}}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - targetPort: {{ dig "SERVER_PORT" "" .Values.env }}
      protocol: TCP
      port: 80
      name: web